export const films = [
  {
    namn: "The Shawshank Redemption",
    selected: true,
    isDisabled: false,
    year: 1994,
    id: 1,
  },
  {
    namn: "The Godfather",
    selected: true,
    isDisabled: false,
    year: 1972,
    id: 2,
  },
  {
    namn: "The Godfather: Part II",
    selected: true,
    isDisabled: false,
    year: 1974,
    id: 3,
  },
  {
    namn: "The Dark Knight",
    selected: true,
    isDisabled: false,
    year: 2008,
    id: 4,
  },
  {
    namn: "12 Angry Men",
    selected: true,
    isDisabled: false,
    year: 1957,
    id: 5,
  },
  {
    namn: "Schindler's List",
    selected: true,
    isDisabled: false,
    year: 1993,
    id: 6,
  },
  {
    namn: "Pulp Fiction",
    selected: true,
    isDisabled: false,
    year: 1994,
    id: 7,
  },
  {
    namn: "The Lord of the Rings: The Return of the King",
    selected: true,
    isDisabled: false,
    year: 2003,
    id: 8,
  },
  {
    namn: "The Good, the Bad and the Ugly",
    selected: false,
    isDisabled: false,
    year: 1966,
    id: 9,
  },
  {
    namn: "Fight Club",
    selected: false,
    isDisabled: false,
    year: 1999,
    id: 10,
  },
  {
    namn: "The Lord of the Rings: The Fellowship of the Ring",
    selected: false,
    isDisabled: false,
    year: 2001,
    id: 11,
  },
  {
    namn: "Star Wars: Episode V - The Empire Strikes Back",
    selected: false,
    isDisabled: false,
    year: 1980,
    id: 12,
  },
  {
    namn: "Forrest Gump",
    selected: false,
    isDisabled: false,
    year: 1994,
    id: 13,
  },
  {
    namn: "Inception",
    selected: false,
    isDisabled: false,
    year: 2010,
    id: 14,
  },
  {
    namn: "The Lord of the Rings: The Two Towers",
    selected: false,
    isDisabled: false,
    year: 2002,
    id: 15,
  },
  {
    namn: "One Flew Over the Cuckoo's Nest",
    selected: false,
    isDisabled: false,
    year: 1975,
    id: 16,
  },
  {
    namn: "Goodfellas",
    selected: false,
    isDisabled: false,
    year: 1990,
    id: 17,
  },
  {
    namn: "The Matrix",
    selected: false,
    isDisabled: false,
    year: 1999,
    id: 18,
  },
  {
    namn: "Seven Samurai",
    selected: false,
    isDisabled: false,
    year: 1954,
    id: 19,
  },
  {
    namn: "Star Wars: Episode IV - A New Hope",
    selected: false,
    isDisabled: false,
    year: 1977,
    id: 20,
  },
  {
    namn: "City of God",
    selected: false,
    isDisabled: false,
    year: 2002,
    id: 21,
  },
  { namn: "Se7en", selected: false, isDisabled: false, year: 1995, id: 22 },
  {
    namn: "The Silence of the Lambs",
    selected: false,
    isDisabled: true,
    year: 1991,
    id: 23,
  },
  {
    namn: "It's a Wonderful Life",
    selected: false,
    isDisabled: true,
    year: 1946,
    id: 24,
  },
  { namn: "Life Is Beautiful", selected: false, isDisabled: true, year: 1997 },
  {
    namn: "The Usual Suspects",
    selected: false,
    isDisabled: true,
    year: 1995,
    id: 25,
  },
  {
    namn: "Léon: The Professional",
    selected: false,
    isDisabled: true,
    year: 1994,
    id: 26,
  },
  {
    namn: "Spirited Away",
    selected: false,
    isDisabled: true,
    year: 2001,
    id: 27,
  },
  {
    namn: "Saving Private Ryan",
    selected: false,
    isDisabled: false,
    year: 1998,
    id: 28,
  },
  {
    namn: "Once Upon a Time in the West",
    selected: false,
    isDisabled: false,
    year: 1968,
    id: 29,
  },
  {
    namn: "American History X",
    selected: false,
    isDisabled: false,
    year: 1998,
    id: 30,
  },
  {
    namn: "Interstellar",
    selected: false,
    isDisabled: false,
    year: 2014,
    id: 31,
  },
  {
    namn: "Casablanca",
    selected: false,
    isDisabled: false,
    year: 1942,
    id: 32,
  },
  {
    namn: "City Lights",
    selected: false,
    isDisabled: false,
    year: 1931,
    id: 33,
  },
  { namn: "Psycho", selected: false, isDisabled: false, year: 1960, id: 34 },
  {
    namn: "The Green Mile",
    selected: false,
    isDisabled: false,
    year: 1999,
    id: 35,
  },
  {
    namn: "The Intouchables",
    selected: false,
    isDisabled: false,
    year: 2011,
    id: 36,
  },
  {
    namn: "Modern Times",
    selected: false,
    isDisabled: false,
    year: 1936,
    id: 37,
  },
];
