# Use YAML syntax version 2.1
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/*
      - fix/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Semantic Release
        if: ${{github.ref == 'refs/heads/main'}}
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [
              {
                name: 'main'
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

      - name: Semantic Release
        if: ${{github.ref != 'refs/heads/main'}}
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [         
              {
                name: '${{ github.ref }}',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
