name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/*
      - fix/*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set conditional variable
        run: |
          CURRENT_BRANCH=$(echo "${GITHUB_REF#refs/heads/}")        
          if [ '${{ github.ref }}' == 'refs/heads/main' ]; then
            PRERELEASE_BRANCH="-"
          else
            PRERELEASE_BRANCH="$CURRENT_BRANCH"
          fi
        env:
          PRERELEASE_BRANCH: ${{ env.PRERELEASE_BRANCH }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [
              {
                name: 'main'
              },              
              {
                name: '${{ env.PRERELEASE_BRANCH }}',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
