name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/*
      - fix/*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SET CURRENT_BRANCH
        run: |
          echo "${GITHUB_REF}"
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")
          echo "${branch_name}"
          echo "CURRENT_BRANCH=$branchName" >> $GITHUB_ENV

      - name: Set conditional variable
        run: |
          CURRENT_BRANCH=$(echo "${GITHUB_REF#refs/heads/}")      
          echo $CURRENT_BRANCH

          if [ '${{ github.ref }}' == 'refs/heads/main' ]; then
            echo PRERELEASE_BRANCH="-" >> $GITHUB_ENV
          else
            echo "PRERELEASE_BRANCH=$CURRENT_BRANCH" >> $GITHUB_ENV
            echo $CURRENT_BRANCH
            echo "${{ env.PRERELEASE_BRANCH }}"
          fi

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [
              {
                name: 'main'
              },              
              {
                name: '${{ env.PRERELEASE_BRANCH }}',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
