# Use YAML syntax version 2.1
name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/*
      - fix/*

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      PRERELEASE_BRANCH: ${{ if github.ref == 'refs/heads/main' }}-${{ else }}${{ github.ref }}${{ endif }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [
              {
                name: 'main'
              },              
              {
                name: '${{ env.PRERELEASE_BRANCH }}',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
