name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/*
      - fix/*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SET CURRENT_BRANCH
        run: |
          $branchName = "${{github.ref}}".Split("/")["${{github.ref}}".Split("/").Length -1]
          echo "::set-env name=CURRENT_BRANCH::$(echo $branchName)"

      - name: Set conditional variable
        run: |
          if [ '${{ github.ref }}' == 'refs/heads/main' ]; then
            PRERELEASE_BRANCH="-"
          else
            PRERELEASE_BRANCH="${{ env.CURRENT_BRANCH }}"
          fi
        env:
          PRERELEASE_BRANCH: ${{ env.PRERELEASE_BRANCH }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          branches: |
            [
              {
                name: 'main'
              },              
              {
                name: '${{ env.PRERELEASE_BRANCH }}',
                prerelease: true
              }
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
