name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

env:
  GH_TOKEN: ${{ secrets.GITHUBTOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - run: npm ci
      - run: npm run build --if-present
      - run: npx semantic-release
